spring:
  application:
    name: subscriptionhub
db:
  jdbcUrl: jdbc:postgresql://localhost:5432/subscription_system
  username: boomzin
  password: boomzin
  driverClassName: org.postgresql.Driver
  maximumPoolSize: 20
  minimumIdle: 1
  idleTimeout: 60000