spring:
  application:
    name: subscriptionhub
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/subscription_system
    username: boomzin
    password: boomzin
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 20
    minimumIdle: 1
    idleTimeout: 60000

security:
  private-key:
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJcYO85ArLQ1NcpmrVsAA4eD9U
    wvQgzMZPRVHTl5yuKIEhiVBJN7zlDXr55e1dmK4M1c4SRJigRT0/WVIGN0YF6dfxEgoUzmE58X1r
    AMaybJhsF5MIouth/ajUeSovqcnR1N8dSQuxOtPP1diraeU/oIRigN7pAbbfZTO+WudiSHHmrChd
    i5wFVa8zGaWE1r0juZ/xw6IaAYLsGqR+blQ5ty0JSIKQWrG6oa0wngYQZk6hpimM86CWIZMfi8Gq
    a3eomwTg4BcaypqLfw2PrjiA38psqwFBf0Rdd7SwCwaq4xMHLtyAhxvWcE0vogu6buGYZvmFQSnR
    C/kYaCOGanWJAgMBAAECggEADmaEAWPX9bHpaq0m5AHB8kd+V4PcSd/5qT8OW27yL20L1ibny2Ql
    p8Yv7V9neZJpltdN9PZcZtCsUTQEbhdTdSbDXiNo/xXF04uU6KpUifrDZq7EvxBOfWHRyOakgmXD
    3LE4BfLr2A6Zh7kE1TQrxEGoVRZbWRLbTNsCOPBsrBTbPuSqn4M3S7iKKcH6E3SuOMsQPonQ/bQD
    ZFI+RgSN3nPZDnd0n31+LkflpzSe9noQ5igbC6g+kP4bBT69It95XiMb7hV91J7vngsuOM2cPsUs
    G7GzAI5DWpiDiF8XtcMH96AWyGSLNqe2lJ8/YLpZIBw3bViCCZnwFQW/4uRlgQKBgQDfwaW6cn3D
    0+xyY7BQmOwqsmWEQV+kMySR0Yyzr2him1xz0UcPOh9+dLaWU1FmevMHbA2ExMEJFKlJiaHHkUcg
    QE/Hy/iFzyP6Sv22xqDNmbs5hCC3n+T5fglo48OJm4BwR+buZgIKqz5xPZdZvGyOpjGDwMCUnzbz
    6cIG38MRkQKBgQDmeL3/971r1yaUfsBi4unhGhqDUBtzyrjRZI9wKoEPPANugVzOz7H01EH5dhCP
    5WQDKtTZQHMqwRd106xRxBW9HkgsyaOK13BoWpSq/YSzEJf6RC+nAFaYawyyljQkADV2EYPLwwTz
    tJ/lb1iri7ZFCrmAZGPD6HLYUqre7LCoeQKBgF5n8semtL9h89oTi3mF++bL3B8gAf1igqRveGD7
    uhwYlrpa6xNWn6EYF013m9mUOGPCSDXjWdq99+sKAdMUzaCi4cZXneS/D9vztfZe+culeCP9RlyT
    PuWxMsEpj//INzmobJvbODNOKwtWRDxdTqQlJLEFK3vJbUMeNnn2APSxAoGBAK8xdWzQS8NgJ0mW
    GHSS/SpKB4FuMZARt/AkOw0OolCMVCd6WqwzIZl0iDozT1+zBhWKR4ZmAaWsZkMBBuqY3dWG4WJ6
    XME8B4yr3nskf+0GXiC2GGsgTLNMHLjciQIczobTxZXsxyTiVvG3dHXinElbX6uDpHrVhgd+v7j5
    v0gxAoGAEYcahk/aqR5GsAUPhXCeSi+56x+Udv1wdkyGp3GZY+0L/TCtGQO5Z2q9VN1/v3W/WhIB
    FshFZxex349SfbXSLnZK2k0UlLhNLC7VPXLQ4nC7KEEfgwQanRqG3v1l5HCfuCtNWbLBD6fC91EK
    yx229LUgn5WtqGnD3nnCQgWgZM8=
    -----END PRIVATE KEY-----